name: NoItem
version: ${project.version}-${BUILD_NUMBER}
website: http://dev.bukkit.org/server-mods/noitem/
description: An advanced item control plugin which also supports custom blocks.
authors: [nala3]

main: net.worldoftomorrow.noitem.NoItem
database: false
softdepend: [Vault]

commands:
    noitem:
        description: NoItems only command, used to reload the config
        usage: /noitem [reload]